[package]
name = "s2-api"
version = "0.1.0"
authors = ["Tanner Donovan <ttdonovan@gmail.com>"]

build = "build.rs"

[dependencies]
bytes = "0.4"
prost = "0.2"
prost-derive = "0.2"

[build-dependencies]
prost-build = "0.2"
